// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcI3Cx5tvzN5PkGMwc6WNxHHJEa4mnbsE',
    appId: '1:932089823808:web:0da0beb449f65a297155a5',
    messagingSenderId: '932089823808',
    projectId: 'pajajap-b809b',
    authDomain: 'pajajap-b809b.firebaseapp.com',
    storageBucket: 'pajajap-b809b.firebasestorage.app',
    measurementId: 'G-GYT41YGXVS',
    databaseURL:
        'https://pajajap-b809b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwYqsbrgbx3P3tI0ZcJpL1w_qLrMrJNiQ',
    appId: '1:932089823808:android:f18efcb9a44724f47155a5',
    messagingSenderId: '932089823808',
    projectId: 'pajajap-b809b',
    storageBucket: 'pajajap-b809b.firebasestorage.app',
    databaseURL:
        'https://pajajap-b809b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-avTZw7u0VhJr956FfWsh1LF5RUXoDwQ',
    appId: '1:932089823808:ios:26c4e45b5c72d8747155a5',
    messagingSenderId: '932089823808',
    projectId: 'pajajap-b809b',
    storageBucket: 'pajajap-b809b.firebasestorage.app',
    iosClientId:
        '932089823808-ffgjoeba48fkmpvenksmqfa8nqjveb3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePasar',
    databaseURL:
        'https://pajajap-b809b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-avTZw7u0VhJr956FfWsh1LF5RUXoDwQ',
    appId: '1:932089823808:ios:26c4e45b5c72d8747155a5',
    messagingSenderId: '932089823808',
    projectId: 'pajajap-b809b',
    storageBucket: 'pajajap-b809b.firebasestorage.app',
    iosClientId:
        '932089823808-ffgjoeba48fkmpvenksmqfa8nqjveb3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePasar',
    databaseURL:
        'https://pajajap-b809b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcI3Cx5tvzN5PkGMwc6WNxHHJEa4mnbsE',
    appId: '1:932089823808:web:c16afcefd1e430337155a5',
    messagingSenderId: '932089823808',
    projectId: 'pajajap-b809b',
    authDomain: 'pajajap-b809b.firebaseapp.com',
    storageBucket: 'pajajap-b809b.firebasestorage.app',
    measurementId: 'G-K9673D09M5',
    databaseURL:
        'https://pajajap-b809b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
